{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"financials\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "financials": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "financials": {
                      "State": "Generated"
                    }
                  },
                  {
                    "financials": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "financials.cog": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "COGS"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cog": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cog": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "mechanism": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "cogwheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "gearwheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "flywheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "component": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "gear": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "wheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "financials.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "hierarquia de data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "hierarquia de data": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "hierarquia de information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Ano",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date ano": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Dia",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dia": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date dia": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Mês",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mê": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Trimestre",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trimestre": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date trimestre": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.discount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Discounts"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "rebate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.discount_band": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Discount Band"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "discount band": {
                      "State": "Generated"
                    }
                  },
                  {
                    "discount band": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "band": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "band": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount posse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "posse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "discount group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount gang": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount crew": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount crowd": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount mob": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "gang": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crew": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crowd": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.gross_sale": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Gross Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "gross sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "gross sale": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "aggregate sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "overall sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "whole sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "sum sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "gross auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "gross transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "gross deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "gross trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "gross vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "financials.manufacturing_price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Manufacturing Price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "manufacturing price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "manufacturing price": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "manufacturing value": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "financials.month_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Month Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month name": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "financials.month_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Month Number"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month number": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month number": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month no": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth number": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "financials.product": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Product"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.profit": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Profit"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "profit": {
                      "State": "Generated"
                    }
                  },
                  {
                    "profit": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "revenue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "return": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "advantage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "gain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "benefit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "use": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "reward": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "financials.sale": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": " Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    " Sales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "Sales": {
                      "State": "Generated",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "Sales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "retailing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "selling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "financials.sale_price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Sale Price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sale price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale price": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale value": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "financials.segment": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Segment"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "segment": {
                      "State": "Generated"
                    }
                  },
                  {
                    "segment": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "division": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "subdivision": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "sector": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "bit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "fragment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "piece": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "slice": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.unit_sold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Units Sold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "unit sold": {
                      "State": "Generated"
                    }
                  },
                  {
                    "unit sold": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "module sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "element sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "entity sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "group sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "component sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "constituent sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "item sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "part sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "section sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "financials.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "financials_date_has_variation_hierarquia_de_data": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      },
                      "Subject": {
                        "Role": "financials.date"
                      }
                    },
                    "ID": "dates_have_hierarquia_de_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date": {
                    "Target": {
                      "Entity": "financials.date"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_ano_has_financials_date_variation_hierarquia_de_data_trimestre": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      }
                    },
                    "ID": "anos_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "ID": "trimestres_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "trimestres_are_in_anos",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.ano": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.ano"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_ano": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.ano": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_dia": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.dia": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.dia"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_mê": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_trimestre": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_mê_has_financials_date_variation_hierarquia_de_data_dia": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "ID": "mê_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      }
                    },
                    "ID": "dias_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "dias_are_in_mê",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.dia": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.dia"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_trimestre_has_financials_date_variation_hierarquia_de_data_mê": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "ID": "trimestres_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "ID": "mê_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "mê_are_in_trimestres",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_cog": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.cog"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_cogs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.cog": {
                    "Target": {
                      "Entity": "financials.cog"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_country": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.country"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.country": {
                    "Target": {
                      "Entity": "financials.country"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_date": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.date": {
                    "Target": {
                      "Entity": "financials.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_discount": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.discount"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_discounts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.discount": {
                    "Target": {
                      "Entity": "financials.discount"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_discount_band": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.discount_band"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_discount_bands",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.discount_band": {
                    "Target": {
                      "Entity": "financials.discount_band"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_gross_sale": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.gross_sale"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_gross_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.gross_sale": {
                    "Target": {
                      "Entity": "financials.gross_sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.month_name"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.month_name": {
                    "Target": {
                      "Entity": "financials.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_month_number": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.month_number"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_month_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.month_number": {
                    "Target": {
                      "Entity": "financials.month_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_product": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.product"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_products",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.product": {
                    "Target": {
                      "Entity": "financials.product"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_profit": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.profit"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_profits",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.profit": {
                    "Target": {
                      "Entity": "financials.profit"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_sale": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.sale"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.sale": {
                    "Target": {
                      "Entity": "financials.sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_segment": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.segment"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_segments",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.segment": {
                    "Target": {
                      "Entity": "financials.segment"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_unit_sold": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.unit_sold"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_unit_sold",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.unit_sold": {
                    "Target": {
                      "Entity": "financials.unit_sold"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_year": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.year"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.year": {
                    "Target": {
                      "Entity": "financials.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_in_country": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "ID": "financials_are_in_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.country": {
                    "Target": {
                      "Entity": "financials.country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "financials.country"
                  }
                },
                "State": "Generated"
              },
              "financials_is_expensive": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "financials.manufacturing_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "manufacturing_price_indicates_how_expensive_financials_are",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.manufacturing_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_manufacturing_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.manufacturing_price": {
                    "Target": {
                      "Entity": "financials.manufacturing_price"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_is_expensive1": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "financials.sale_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "sale_price_indicates_how_expensive_financials_are",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.sale_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_sale_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.sale_price": {
                    "Target": {
                      "Entity": "financials.sale_price"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "c72e7f86-19af-4bff-a338-a51ab54907a6",
        "fromColumn": "Date",
        "fromTable": "financials",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a776e97b-9c43-4b3a-9fb4-018fbf6ba054"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "financials",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5c43dec-9cc4-4f23-96ad-1e49c80044d1",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08645993-cf3f-4696-82d6-045ae6f3c7b9",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f00b263-c859-4816-a45f-e150fd3f70c1",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdd1ff89-19fb-47f1-af1e-c3a8f25e6d8d",
            "sourceColumn": "Discount Band",
            "summarizeBy": "none"
          },
          {
            "name": "Units Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d0e3ecb-5d25-46f7-a037-74813399711e",
            "sourceColumn": "Units Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f2c2a43-d460-486e-8d08-e81fd010a7d6",
            "sourceColumn": "Manufacturing Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8adde69d-17c6-4bad-9c38-71fae327bf6d",
            "sourceColumn": "Sale Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "827cfbd4-38df-4352-b2b2-537693ccb3e1",
            "sourceColumn": "Gross Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Discounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "259eb6af-e581-4b24-ade9-b7a7149abbbe",
            "sourceColumn": "Discounts",
            "summarizeBy": "sum"
          },
          {
            "name": " Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0734507f-b7d1-4cd2-bf01-4ca298642607",
            "sourceColumn": " Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77dfaa81-4eea-4aab-b09a-ed4997c03958",
            "sourceColumn": "COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8cd9063f-4e38-43ed-afba-2b27b0039c88",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4a0d888e-cfab-4815-9181-4d68b0578205",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_a776e97b-9c43-4b3a-9fb4-018fbf6ba054"
                },
                "isDefault": true,
                "relationship": "c72e7f86-19af-4bff-a338-a51ab54907a6"
              }
            ]
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97f1e656-b8e2-4e6e-90d3-a40440e2c858",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27f8658c-7128-44dc-a291-5cdc93c4e87b",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a7395f0-f2cd-4bdf-86eb-27a4355d29ba",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "fbd37eb6-d36a-412e-bbd9-1c9c58c5e36e",
        "partitions": [
          {
            "name": "financials",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\jeffersonlima\\Documents\\GitHub\\dio-exercices\\Sysvision - Data Analytics com power Bi\\Desafio 01\\Financial Sample.xlsx\"), null, true),",
                "    financials_Table = Fonte{[Item=\"financials\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(financials_Table,{{\"Segment\", type text}, {\"Country\", type text}, {\"Product\", type text}, {\"Discount Band\", type text}, {\"Units Sold\", type number}, {\"Manufacturing Price\", Int64.Type}, {\"Sale Price\", Int64.Type}, {\"Gross Sales\", type number}, {\"Discounts\", type number}, {\" Sales\", type number}, {\"COGS\", type number}, {\"Profit\", type number}, {\"Date\", type date}, {\"Month Number\", Int64.Type}, {\"Month Name\", type text}, {\"Year\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_c9eb83aa-c628-4292-88c3-890fa17b6f9a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cad23cef-d097-414d-a83d-17ea785bec15",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "06fab7b9-ef3b-418c-bd64-ee3616f2185b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9b0c87a2-7730-49d0-af48-f25a956b629c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "139a750e-010e-4934-92a0-ce2ffe5952dd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9cf347d-3edd-4c96-82f3-f5ce138c953c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d501332a-4af3-4c2a-a5b3-32f6d36b081b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f896fe90-442f-4b73-9c5a-c9dc40664e7a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "aa4bd9cd-2ba9-4886-8762-00ad8316d3d0",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "dbbe2ddf-b62e-4445-8b95-d751cdb1daad",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "4e7c5222-9efe-4fe1-8a94-87344dd42d1b",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "4ea72a56-784a-47e8-a3ee-586947e4d7d4",
                "ordinal": 3
              }
            ],
            "lineageTag": "112e3a72-812f-4803-9648-68f63f3c844c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "132a76eb-f26f-442b-bc50-140f5ad9862e",
        "partitions": [
          {
            "name": "DateTableTemplate_c9eb83aa-c628-4292-88c3-890fa17b6f9a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a776e97b-9c43-4b3a-9fb4-018fbf6ba054",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4b9d2367-94d8-46eb-a200-4f7c7c5e4764",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "839cb4b2-c3d6-411d-81c5-d111bfb1c5d7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74052406-2db1-4183-91b5-e484280b51e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91f088a9-a5c0-45bd-9262-394656387ebe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d1680310-ee4c-4592-ba16-096117e57282",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7f8b3a7a-4492-468c-90d2-6b61243d92d1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "310d9a8b-0a3d-44e5-af2b-13c47fa56e84",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c5a8c144-5f02-488c-92bc-20dbf8e0819b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9ef55c3f-6a46-4628-984f-bab2b0f3053d",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "8c0e7467-66e1-4440-a6d2-d9a227343fe7",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e6022274-2914-4a37-92ca-62f8fcfe2125",
                "ordinal": 3
              }
            ],
            "lineageTag": "5d91b72f-917e-4b8f-9ee9-cd16d4ffa2d0"
          }
        ],
        "isHidden": true,
        "lineageTag": "f54819f2-b56a-4d81-85d3-90afa4e0d62d",
        "partitions": [
          {
            "name": "LocalDateTable_a776e97b-9c43-4b3a-9fb4-018fbf6ba054",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('financials'[Date])), 1, 1), Date(Year(MAX('financials'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}